/*
   Copyright 2016 Aldo J. Nunez

   Licensed under the Apache License, Version 2.0.
   See the LICENSE text file for details.
*/

#pragma once


enum ObjType
{
    Obj_None,

    Obj_BlueLynel,
    Obj_RedLynel,
    Obj_BlueMoblin,
    Obj_RedMoblin,
    Obj_BlueGoriya,
    Obj_RedGoriya,
    Obj_RedSlowOctorock,
    Obj_RedFastOctorock,
    Obj_BlueSlowOctorock,
    Obj_BlueFastOctorock,
    Obj_RedDarknut,
    Obj_BlueDarknut,
    Obj_BlueTektite,
    Obj_RedTektite,
    Obj_BlueLeever,
    Obj_RedLeever,
    Obj_Zora,
    Obj_Vire,
    Obj_Zol,
    Obj_ChildGel,
    Obj_Gel,
    Obj_PolsVoice,
    Obj_LikeLike,
    Obj_LittleDigdogger,
    Obj_Unknown1__,
    Obj_Peahat,
    Obj_BlueKeese,
    Obj_RedKeese,
    Obj_Unknown2__,
    Obj_Armos,
    Obj_Boulders,
    Obj_Boulder,
    Obj_Ghini,
    Obj_FlyingGhini,
    Obj_BlueWizzrobe,
    Obj_RedWizzrobe,
    Obj_PatraChild1,
    Obj_PatraChild2,
    Obj_Wallmaster,
    Obj_Rope,
    Obj_Unknown5__,
    Obj_Stalfos,
    Obj_Bubble1,
    Obj_Bubble2,
    Obj_Bubble3,
    Obj_Whirlwind,
    Obj_PondFairy,
    Obj_Gibdo,
    Obj_3Dodongos,
    Obj_1Dodongo,
    Obj_BlueGohma,
    Obj_RedGohma,
    Obj_RupieStash,
    Obj_Grumble,
    Obj_Zelda,
    Obj_Digdogger1,
    Obj_Digdogger2,
    Obj_RedLamnola,
    Obj_BlueLamnola,
    Obj_Manhandla,
    Obj_Aquamentus,
    Obj_Ganon,
    Obj_GuardFire,
    Obj_StandingFire,
    Obj_Moldorm,
    Obj_Gleeok1,
    Obj_Gleeok2,
    Obj_Gleeok3,
    Obj_Gleeok4,
    Obj_GleeokHead,
    Obj_Patra1,
    Obj_Patra2,
    Obj_Trap,
    Obj_TrapSet4,

    Obj_Person1,
    Obj_Person2,
    Obj_Person3,
    Obj_Person4,
    Obj_Person5,
    Obj_Person6,
    Obj_Person7,
    Obj_Person8,

    Obj_FlyingRock,
    Obj_Unknown54__,
    Obj_Fireball,
    Obj_Fireball2,
    Obj_PlayerSwordShot,

    Obj_OldMan,
    Obj_OldWoman,
    Obj_Merchant,
    Obj_FriendlyMoblin,

    Obj_MagicWave = Obj_OldMan,
    Obj_MagicWave2 = Obj_OldWoman,
    Obj_Arrow = Obj_FriendlyMoblin,

    Obj_Boomerang,
    Obj_DeadDummy,
    Obj_FluteSecret,
    Obj_Ladder,
    Obj_Item,

    Obj_Dock,
    Obj_Rock,
    Obj_RockWall,
    Obj_Tree,
    Obj_Headstone,

    Obj_Unknown66__,
    Obj_Unknown67__,
    Obj_Block,
    Obj_Unknown69__,

    Obj_Cave1,
    Obj_Cave2,
    Obj_Cave3,
    Obj_Cave4,
    Obj_Cave5,
    Obj_Cave6,
    Obj_Cave7,
    Obj_Cave8,
    Obj_Cave9,
    Obj_Cave10,
    Obj_Cave11,
    Obj_Cave12,
    Obj_Cave13,
    Obj_Cave14,
    Obj_Cave15,
    Obj_Cave16,
    Obj_Cave17,
    Obj_Cave18,
    Obj_Cave19,
    Obj_Cave20,

    Obj_Bomb,
    Obj_PlayerSword,
    Obj_Fire,
    Obj_Rod,
    Obj_Food,

    Obj_Player,

    Obj_Person_End          = Obj_Person8 + 1,
    Obj_CaveMedicineShop    = Obj_Cave11,
    Obj_CaveShortcut        = Obj_Cave5,
};

enum
{
    PersonTypes = Obj_Person_End - Obj_Person1,
};
