/*
   Copyright 2016 Aldo J. Nunez

   Licensed under the Apache License, Version 2.0.
   See the LICENSE text file for details.
*/

#pragma once


enum
{
    Anim_PI_LinkWalk_NoShield_Right,
    Anim_PI_LinkWalk_NoShield_Left,
    Anim_PI_LinkWalk_NoShield_Down,
    Anim_PI_LinkWalk_NoShield_Up,
    Anim_PI_LinkWalk_LittleShield_Right,
    Anim_PI_LinkWalk_LittleShield_Left,
    Anim_PI_LinkWalk_LittleShield_Down,
    Anim_PI_LinkWalk_LittleShield_Up,
    Anim_PI_LinkWalk_BigShield_Right,
    Anim_PI_LinkWalk_BigShield_Left,
    Anim_PI_LinkWalk_BigShield_Down,
    Anim_PI_LinkWalk_BigShield_Up,
    Anim_PI_LinkThrust_Right,
    Anim_PI_LinkThrust_Left,
    Anim_PI_LinkThrust_Down,
    Anim_PI_LinkThrust_Up,
    Anim_PI_LinkLiftLight,
    Anim_PI_LinkLiftHeavy,
    Anim_PI_SwordItem,
    Anim_PI_FleshItem,
    Anim_PI_RecorderItem,
    Anim_PI_CandleItem,
    Anim_PI_ArrowItem,
    Anim_PI_BowItem,
    Anim_PI_MKeyItem,
    Anim_PI_KeyItem,
    Anim_PI_RuppeeItem,
    Anim_PI_BombItem,
    Anim_PI_BoomerangItem,
    Anim_PI_Spark,
    Anim_PI_Slash,
    Anim_PI_BottleItem,
    Anim_PI_BookItem,
    Anim_PI_Fireball,
    Anim_PI_RingItem,
    Anim_PI_MSwordItem,
    Anim_PI_WandItem,
    Anim_PI_MapItem,
    Anim_PI_BraceletItem,
    Anim_PI_Fairy,
    Anim_PI_MShieldItem,
    Anim_PI_Heart,
    Anim_PI_Fire,
    Anim_PI_Sparkle,
    Anim_PI_Clock,
    Anim_PI_HeartContainer,
    Anim_PI_Compass,
    Anim_PI_Raft,
    Anim_PI_TriforcePiece,
    Anim_PI_Cloud,
    Anim_PI_Ladder,
    Anim_PI_Wave_Right,
    Anim_PI_Wave_Left,
    Anim_PI_Wave_Down,
    Anim_PI_Wave_Up,
    Anim_PI_Sword_Right,
    Anim_PI_Sword_Left,
    Anim_PI_Sword_Down,
    Anim_PI_Sword_Up,
    Anim_PI_Arrow_Right,
    Anim_PI_Arrow_Left,
    Anim_PI_Arrow_Down,
    Anim_PI_Arrow_Up,
    Anim_PI_Wand_Right,
    Anim_PI_Wand_Left,
    Anim_PI_Wand_Down,
    Anim_PI_Wand_Up,
    Anim_PI_Boomerang,
    Anim_PI_OldMan,
    Anim_PI_OldWoman,
    Anim_PI_Merchant,
    Anim_PI_Moblin,
    Anim_PI_PowerTriforce,
    Anim_PI_Cursor,
};
